name: silly_hacks
description: My submission for [Silly Hacks Hackathon](https://sillyhacks.online)
publish_to: 'none'
authors:
  - Tirth Patel
homepage: https://github.com/piedcipher/silly-hacks
repository: https://github.com/piedcipher/silly-hacks
issue_tracker: https://github.com/piedcipher/silly-hacks/issues
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  demoji:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true